### ISSUE TITLE
Adding PictureBox

### ISSUE THREAD

**Issue by i3igi3yrd** [adamdriscoll/poshprotools#48] opened 2017-09-22 03:16 UTC
When selecting an image for PictureBox, I get the error:

Error invoking 'Choose Image...'. Details:
Value cannot be null.
Parameter name: docData

This is happening on multiple machines.

**Comment by i3igi3yrd** [comment] 2017-09-22 03:17
Update: saw the bug. 
Somehow missed it before posting.

**Comment by adamdriscoll** [comment] 2017-09-22 17:47
@i3igi3yrd Yep. Duplicate of #19

**Closed by adamdriscoll** 2017-09-22 17:47 UTC

**Comment by adamdriscoll** [comment] 2018-01-21 23:50
@i3igi3yrd This is implemented in the next version and will be out in the next couple days.
